app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('user/', include('userauthentication.urls', namespace='userauthentication')),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

main/urls.py
from pydoc import visiblename
from unicodedata import name
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('chat/room/<str:room_name>', views.ChatRoom.as_view(), name='chat_room')
]

userauthentication/urls.py
from django.urls import path

from . import views

app_name = 'userauthentication'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('signup/', views.UserSignUpView.as_view(), name='signup'),
    path('logout/', views.logout_user, name='logout')
]

userauthentication/forms.py
from attr import fields
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserLoginForm(forms.Form):
    pass

class UserRegistraionForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email']

class UserSignupForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

main/views.py
import email
import json
from html import escape

import redis
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

redis_client = redis.Redis(host='localhost', port=6379, db=0)


class ChatRoom(LoginRequiredMixin, View):
    login_url = 'userauthentication:login'
    redirect_field_name = 'redirect_to'
    
    def get(self, req, room_name):
        _chat_members = {}
        _is_host = None
        
        for key in redis_client.scan_iter(room_name[0] + '*'):

            if key.decode() == room_name:
                username = req.user.username.title()
                
                if redis_client.hget(room_name, 'host') != None:
                    if  username == redis_client.hget(room_name, 'host').decode():
                        _is_host = True
                    
                for key in redis_client.hkeys(room_name):
                    if key.decode() == 'host' or key.decode() == 'password':
                        continue
                        
                    _chat_members[key.decode()] = redis_client.hget(room_name, key.decode())

                return render(req, 'main/main.html', {'room_name': room_name, 
                                                    'username': username, 
                                                    'chat_members': _chat_members,
                                                    'is_host': _is_host,
                                                    })
            
        return HttpResponseRedirect(reverse('main:home'))


class HomePage(LoginRequiredMixin, View):
    login_url = 'userauthentication:login'
    redirect_field_name = 'redirect_to'
    
    def get(self, req):
        username = req.user.username
        return render(req, 'main/home.html', {'username': username})

    def post(self, req):
        _room = False

        username = req.user.username
        room_name = req.POST.get("room-name")
        password = req.POST.get('password')
        room_type = req.POST.get('room_type')
        
        if room_type == 'c':

            for key in redis_client.scan_iter(room_name[0] + '*'):

                if key.decode() == room_name:
                    return render(req, 'main/home.html', {'msg': 'room name already taken',
                                                          'username': username})

            redis_client.hset(room_name, 'password', password)
            return HttpResponseRedirect(reverse('main:chat_room', kwargs={'room_name': room_name}))
                

        elif room_type == 'j':

            for key in redis_client.scan_iter(room_name[0] + '*'):
                
                if key.decode() == room_name:
                    room_password = redis_client.hget(room_name, 'password')
                    room_password = room_password.decode()
                    
                    if password == room_password:
                        return HttpResponseRedirect(reverse('main:chat_room', kwargs={'room_name': room_name}))
                    else:
                        return render(req, 'main/home.html', {'msg': 'Invalid password',
                                                              'username': username})       
            
            return render(req, 'main/home.html', {'msg': 'specified room is not available, Invalid room_name', 'username': username})
                

userauthentication/views.py
from email import message
import re
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

class UserLoginView(View):

    def get(self, req):
        return render(req, 'userauthentication/userlogin.html', {'message': ''})
    
    def post(self, req):
        _user_input = req.POST.get('user_input')
        _password = req.POST.get('password')
        
        if '@' in _user_input:
            user = authenticate(req, emial=_user_input, password=_password)
        else:
            user = authenticate(req, username=_user_input, password=_password)
            
        if user is None:
            message = "Invalid login details, Please try again"
            return render(req, 'userauthentication/userlogin.html', {'message': message})
        else:
            redirect_url = req.GET.get('redirect_to')
            
            login(req, user)
            if redirect_url != None:
                return redirect(redirect_url)
            
            return redirect('/')

def logout_user(req):
        logout(req)
        return HttpResponseRedirect(reverse('userauthentication:login'))

def name_validator(text_data):
    if text_data is None:
        return False
    
    if re.search("^[\w.@+-]+\Z", text_data) is None:
        return False
    else:
        return True


class UserSignUpView(View):
    reg = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!#%*?&]{6,20}$"
    pattern = re.compile(reg)

    def get(self, req):
        return render(req, 'userauthentication/usersignup.html')

    def post(self, req):

        _username = req.POST.get('username')
        _email = req.POST.get('email')
        _first_name = req.POST.get('first_name')
        _last_name = req.POST.get('last_name')
        _password_1 = req.POST.get('password1')
        _password_2 = req.POST.get('password2')
        submit = req.POST.get('submit')

        try:
            if len(_email) > 0:
                if User.objects.filter(email=_email).exists():
                    return JsonResponse({'message': '!email'})
                
            if name_validator(_first_name) == False and len(_first_name) > 0:
                return JsonResponse({'message': '!name', 'from': 'first'})
            
            if name_validator(_last_name) == False and len(_last_name) > 0:
                return JsonResponse({'message': '!name', 'from': 'last'})
            
            if name_validator(_username) is False and len(_username) > 0:
                return JsonResponse({'message': '!username'})
            
            if User.objects.filter(username=_username).exists():
                return JsonResponse({'message': '!available'})
            
        except Exception:
            if _password_1 != None:
                if re.search(UserSignUpView.pattern, _password_1):
                    message = 'pass_valid'
                        
                    if _password_1 == _password_2:
                        message = 'pass_match'
                        print(message)
                            
                    return JsonResponse({'message': message})
                
                else:
                    return JsonResponse({'message': 'not valid'})
        
        if submit == 'submit':
            User.objects.create_user(
                username=_username,
                email=_email,
                password=_password_2,
                first_name=_first_name,
                last_name=_last_name,
            ).save()
            
            return HttpResponseRedirect(reverse('userauthentication:login'))
        
        return HttpResponseRedirect(reverse('userauthentication:signup'))

main/templates/main/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- css -->
    <link rel="stylesheet" href="/static/css/homepage.css">

    <!-- Bootstrap CDN -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

	<!-- jquery CDN -->
	<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400&family=Roboto:wght@400;500;700&family=Secular+One&display=swap" rel="stylesheet">
   
    <title>Python Messenger</title>
</head>
<body>

    <div class="main-container container-fluid ps-0 pe-0">

        <nav class="navbar d-flex flex-row justify-content-between ps-3 pe-5 pb-2 pt-2">
            <div>
                <a class="navbar-brand fs-4 fw-semibold ms-4" href="/">
                <img src="/static/assets/Chat.svg" alt="" width="30" height="24" class="d-inline-block align-text-middle logo me-2">
                Python Messenger
                </a>
            </div>

            <button class="btn btn-sm btn-outline-danger rounded-pill logout-btn">Logout</button>
        </nav>

        <div class="user-section">
            <p class="username fs-4">Hi, {{username}}</p>

            <div class="action-btns">
                <button class="btn btn-primary _btn fw-semibold" id="create">Create Room</button>
                <button class="btn btn-primary _btn ms-4 fw-semibold" id="join">Join Room</button>
            </div>

            <form class="forms rounded" id="_room-creation-form" method="POST" action="">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="formGroupExampleInput" class="form-label">Room Name</label>
                    <input type="text" name='room-name' class="form-control" placeholder="" autocomplete='off' required>
                    <p class="format">Enter a name without whitespace</p>
                </div>
                <div class="mb-3">
                    <label for="formGroupExampleInput2" class="form-label">Password</label>
                    <input type="password" name="password" class="form-control" placeholder="**********" required>
                </div>

                <input type="hidden" name="room_type" value="c">

                <div class="form-btns d-flex flex-row justify-content-evenly"> 
                    <button type="submit" class="btn btn-primary fw-semibold">Create</button>
                    <button type="button" onclick="closeForm(this)" class="btn btn-primary fw-semibold">Close</button:button>
                </div>
            </form>

            <form class="forms rounded" id="_room-joining-form" method="POST" action="">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="formGroupExampleInput" class="form-label">Room Name</label>
                    <input type="text" name='room-name' class="form-control" placeholder="" autocomplete='off' required>
                </div>
                <div class="mb-3">
                    <label for="formGroupExampleInput2" class="form-label">Password</label>
                    <input type="password" name='password' class="form-control" placeholder="**********" required>
                </div>

                <input type="hidden" name="room_type" value="j">

                <div class="form-btns d-flex flex-row justify-content-evenly"> 
                    <button type="submit" class="btn btn-primary fw-semibold">Join</button>
                    <button type="button" onclick="closeForm(this)" class="btn btn-primary fw-semibold">Close</button>
                </div>
            </form>

            {% if msg %}
                <div class="message d-flex flex-row">
                    <img src="/static/assets/Warning.svg" class="err-icon" alt="">
                    <p class="_msg">{{msg}}</p>
                </div>
            {% endif %}

        </div>

    </div>

    <script type="text/javascript">
        
        $('#create').on('click', (e)=> {
            $('#_room-creation-form').css('display', 'block');
            $('#_room-joining-form').css('display', 'none');
        });

        $('#join').on('click', (e)=> {
            $('#_room-joining-form').css('display', 'block');
            $('#_room-creation-form').css('display', 'none');
        });

        function closeForm(e) {

            if (e.parentNode.parentNode.id == '_room-creation-form') {
                $('#_room-creation-form').css('display', 'none');
            } else {
                $('#_room-joining-form').css('display', 'none');
            }
        }

        $('.logout-btn').on('click', () => {
            window.location.href = '{% url 'userauthentication:logout' %}'
        })

    </script>
</body>
</html>

main/templates/main/main.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- css -->
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">

	<!-- Bootstrap CDN -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

	<!-- jquery CDN -->
	<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Secular+One&display=swap" rel="stylesheet">
	
    <title>Python Messenger</title>
</head>
<body>

	<div class="container-fluid" id="main-container">

		<div class="row">

			<!-- left side container -->
			<div class="col-3 mt-1 con-l pe-0">
				<div class="list-group">

					<!-- header -->
					<div class="fixed">
						<nav class="navbar rounded-top bg-dark bg-light">
							<div class="container-fluid">
							  <span class="navbar-brand mb-0 h1 text-white">Room Members</span>
							  <img src="/static/assets/close.svg" class="close-icon" alt="">
							</div>
						</nav>
					</div>

                    <input type="hidden" name="username" value={{username}}>
                    <input type="hidden" name="room_name" value="{{room_name}}">

					<!-- list of participants or members in the chat room -->

					{% if is_host %}
						{% for member in chat_members %}
							<div class="list-group-item list-group-item-action pb-2 pt-3 d-flex flex-row justify-content-between">
								<div class="user-pic d-flex flex-row">
									<p class="pic rounded-circle text-center me-3 bg-success bg-gradient">{{member|slice:2}}</p>
									<p class="room-members-name">{{member}}</p>
								</div>
								<button class="btn btn-danger remove-user fw-semibold  btn-sm">Remove</button>
							</div>
						{% endfor %}
					{% else %}
						{% for member in chat_members %}
							<div class="list-group-item list-group-item-action pb-2 pt-3 d-flex flex-row justify-content-between">
								<div class="user-pic d-flex flex-row">
									<p class="pic rounded-circle text-center me-3 bg-success bg-gradient">{{member|slice:2}}</p>
									<p class="room-members-name">{{member}}</p>
								</div>
							</div>
						{% endfor %}
					{% endif %}

				</div>
			</div>

			<!-- right side container -->
			<div class="col-9 con-r ps-0">

				<!-- header -->
				<div class="fixed-l">
					<nav class="navbar rounded-top bg-light .bg-light.bg-gradient d-flex flex-row">
						<div class="container-fluid">
						  <span class="navbar-brand mb-0 h1 text-black fw-semibold ms-4" style="width: fit-content;">{{room_name}}</span>
                
						  <div class="dropdown">
								<button class="btn btn-primary dropdown-toggle bg-light" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
									<img src="/static/assets/app-indicator.svg" type="button" alt="">
								</button>

								<ul class="dropdown-menu  dropdown-menu-dark notification-section" id="dropdown" aria-labelledby="dropdownMenuButton1">
									
								</ul>
						  </div>

						  <button class="btn btn-danger btn-sm me-2 leave-room fw-semibold">Leave</button>
						</div>
					</nav>
				</div>

				<!-- message logs -->
				<div class="chat-logs ps-2 pt-2">

				</div>

				<!-- message input section -->
				<div class="chat-section d-flex flex-row rounded-bottom">
					<div class="msg-area me-4 ms-4">
						<textarea class="form-control" name="msg-input" id="chat-msg-input" cols="30" rows="10"></textarea>
					</div>

					<button type="button" class="btn btn-primary btn-sm fw-semibold" id="submit-btn">send</button>
				</div>

			</div>
		</div>
	</div>

    <script src="/static/js/chatroomhandler.js"></script>

	<script>
		const mediaQuery = window.matchMedia('(max-width: 545px)')
		// Check if the media query is true
		if (mediaQuery.matches) {
			$('.con-r').css('padding', '0');
			$('#notification').removeClass('dropdown');
			$('#notification').addClass('dropdown-center');
			$('.dropdown-toggle').removeAttr('id');
			$('.dropdown-toggle').attr('id', 'dropdownCenterBtn');
			$('.dropdown-menu').removeAttr('id');
			$('.dropdown-menu').attr('id', 'dropdownCenterBtn');

			$('.navbar-brand').removeClass('ms-4')

			$('.navbar-brand').on('click', () => {
				$('.con-l').css('display', 'block');
				$('.con-l').css('z-index', '2');
				$('.con-l').css('position', 'relative');
				$('.con-l').css('height', '99vh');
				$('.con-l').css('padding-left', '0');
				$('.con-l').removeClass('mt-1');
			});

			$('.close-icon').on('click', ()=> {
				$('.con-l').css('display', 'none');
			})
		}
	</script>
</body>
</html>

main/templates/main/roomlogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- css file -->
    <link rel="stylesheet" href="/static/css/roomlogin.css">

    <title>Python Messenger</title>
</head>
<body>

    <div class="container">
        <div class="login-section">
            <p class="heading">Chat Room Login</p>

            <form method='POST' action='' class="room-login">
                {% csrf_token %}
                <div class="name-section">
                    <label class="name-label" for="username">Username</label>
                    <input type="text" class="name" name="username" placeholder="username" required>
                </div>
                <br>

                <div class="id-section">
                    <label for="room-id" class="room-id-label">Room ID</label>
                    <input type="text" class="room-id" id="room-id" name="room-id" placeholder="room id" required>
                </div>
                
                <div class="form-btns">
                    <button class="btn" type="submit" value="submit" onsubmit="submitForm()">Submit</button>
                    <button class="btn">Cancel</button>
                </div>
            </form>
        </div>
    </div>
    
</body>
</html>

userauthentication/templates/userauthentication/userlogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- css -->
    <link rel="stylesheet" href="/static/css/userlogin.css">

    <!-- Bootstrap CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    <!-- jquery CDN -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" 
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
			crossorigin="anonymous">
    </script>

    <title>Python Messenger</title>
</head>
<body style="width: 100%;">

    <div class="container">

        <form class="signup-form" method='POST' action=''>

            <img class="logo" src="/static/assets/Chat.svg" alt="" class="chat-logo">

            {% csrf_token %}

            <div class="heading">
                <h1>Sign in</h1>
                <p class="txt">Welcome back! Please enter your details</p>
            </div>

            <div class="col">
                <input type="text" class="form-control" placeholder="email id or username" name='user_input' aria-label="email" required>
            </div>

            <div class="col" style="margin-top: 25px;">
                <input type="password" class="form-control" placeholder="password" name='password' aria-label="email" required>
            </div>

            <p class="message">{{message}}</p>

            <div class="row" style="margin-top: 50px;">
                <p class="col">
                    Don't have an account? <a href={% url 'userauthentication:signup' %} style="font-weight: 600;">Sign up</a>
                </p>

                <a href="" class="col forgot-pass" style="text-align: right; text-decoration: none; font-weight: 600;">Forgot password</a>
            </div>

            <button class="btn btn-primary" id="submit-btn" type="submit">Sign in</button>
        </form> 
    </div>

</body>
</html>

userauthentication/templates/userauthentication/userregistration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- css -->
    <link rel="stylesheet" href="/static/css/registrationpage.css">

    <!-- jquery CDN -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" 
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
			crossorigin="anonymous">
    </script>

    <title>Python Messenger</title>
</head>
<body>

    <p>User Registration Form</p>

    <div class="container">
        <form action="" method="POST" class="registration-form">

            {% csrf_token %}
            {{form.username.label}} <br>
            {{form.username}}
            <br>
            {{form.email.label}} <br>
            {{form.email}}
            <br>

            <div class="message-section">
                <p class="message"></p>
            </div>

            <br>
            <button class="submit-btn" id="submit-btn" type="submit" value="submit">continue</button>
        </form>
    </div>

    <div></div>    
</body>
</html>

userauthentication/templates/userauthentication/usersignup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- css -->
    <link rel="stylesheet" href="/static/css/signuppage.css">

    <!-- Bootstrap CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    <!-- jquery CDN -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" 
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
			crossorigin="anonymous">
    </script>

    <title>Python Messenger</title>
</head>
<body style="width: 100%;">

    <div class="container">

        <form method='POST' action=" " class="signup-form">
            {% csrf_token %}
            <img class="logo" src="/static/assets/Chat.svg" alt="" class="chat-logo">

            <h1 class="heading">Sign Up</h1>
            <div class="row">
                <div class="col">
                  <input type="text" name="first_name" class="form-control" placeholder="First name" aria-label="First name" required>
                </div>
                <div class="col">
                  <input type="text" name="last_name" class="form-control" placeholder="Last name" aria-label="Last name" required>
                </div>
                <div class="status">
                    <img id="name-status-icon" src="/static/assets/Warning.svg" alt="" class="status-icon">
                    <p id="name-status-msg">Invalid first or last name</p>
                </div>
            </div>
            <div class="col" id="username-section">
                <input type="text" name="username" class="form-control" placeholder="username" aria-label="username" required  autocomplete="off">
                <div class="status">
                    <img id="username-status-icon" src="/static/assets/Warning.svg" alt="" class="status-icon">
                    <p id="username-status-msg">Username already taken</p>
                </div>
            </div>
            <div class="col" id="email-section">
                <input type="email" name="email" class="form-control" placeholder="email Id" aria-label="email Id" required  autocomplete="off">
                <div class="status">
                    <img id="email-status-icon" src="/static/assets/Warning.svg" alt="" class="status-icon">
                    <p id="email-status-msg">email already taken</p>
                </div>
            </div>
            <div class="row" id="password-section">
                <div class="col">
                  <input type="password" id="password" name="password1" class="form-control" placeholder="password" aria-label="password" required>
                  <img src="/static/assets/visible.svg" alt="" class="pass-show-btn">
                </div>
                <div class="col">
                  <input type="password" id="password" name="password2" class="form-control" placeholder="re-enter your password" aria-label="password" required>
                  <!-- <img src="/static/assets/visible.svg" alt="" class="pass-show-btn"> -->
                </div>
            </div>
            <div class="messages">
                <div class="row">
                    <p class="least-msg">Least 8 characters</p>
                    <img class="icon" id="least-icon" src="/static/assets/wrong.svg" alt="">
                </div>
                <div class="row" style="margin-top: -17px;">
                    <p class="numeric-msg">Least one number (0-9) and a symbol</p>
                    <img class="icon" id="numeric-icon" src="/static/assets/wrong.svg" alt="">
                </div>
                <div class="row" style="margin-top: -17px;">
                    <p class="alpha-msg">Lowercase (a-z) and uppercase (A-Z)</p>
                    <img class="icon" id="alpha-icon" src="/static/assets/wrong.svg" alt="">
                </div>
                <div class="row" style="margin-top: -17px;">
                    <p class="password-match-msg">password matching</p>
                    <img class="icon" id="match-icon" src="/static/assets/wrong.svg" alt="">
                </div>
            </div>

            <div class="row" style="margin-top: 17px;">
                <p class="col">
                    Already a member? <a href={% url 'userauthentication:login' %} style="font-weight: 600;">Log in</a>
                </p>

                {% comment %} <a href="" class="col forgot-pass" style="text-align: right; text-decoration: none; font-weight: 600;">Forgot password</a> {% endcomment %}
            </div>

            <button class="btn btn-primary" id="submit-btn" type='submit' name="submit" value="submit">create account</button>
        </form> 
    </div>

    <script src='/static/js/signupform.js'></script>
</body>
</html>